---
dnsdomain: .pp.buehl.digital
privateVLANID: 4000
privateVLANGeometry: 10.0.0.0/24
privateVLANGateway: 10.0.0.1
hostsblock1: |
  10.0.0.151 signal01.pp.buehl.digital
  10.0.0.152 signal02.pp.buehl.digital
  10.0.0.201 securesignal01.pp.buehl.digital
  10.0.0.101 jvb1.pp.buehl.digital
  10.0.0.102 jvb2.pp.buehl.digital turn.buehl.digital
  10.0.0.103 jvb3.pp.buehl.digital
  10.0.0.104 jvb4.pp.buehl.digital
  10.0.0.105 jvb5.pp.buehl.digital
  10.0.1.2 stats.buehl.digital
ssh_port: 2424
filePathPrefix: inventory/prod_files
letsencrypt_email: "{{ vault_letsencrypt_email }}"
users:
  - itrich
  - gabriel
  - h2invent
mysql_admin_password: "{{ vault_mysql_admin_password }}"
prosody_user_focus_password: "{{ vault_prosody_user_focus_password }}"
prosody_user_jvb_password: "{{ vault_prosody_user_jvb_password }}"
prosody_user_jigasi_password: "{{ vault_prosody_user_jigasi_password }}"
jicofo_secret: "{{ vault_jicofo_secret }}"
jicofo_auth_password: "{{ vault_jicofo_auth_password }}"
component_secret: "{{ vault_component_secret }}"
turncredentials_secret: "{{ vault_turncredentials_secret }}"
app_id:  "{{ vault_app_id }}"
app_secret:  "{{ vault_app_secret }}"
influxdb_database: "jitsi"
influxdb_url: "https://stats.buehl.digital:8086"
influxdb_jitsi_user: "{{ vault_influxdb_jitsi_user }}"
influxdb_jitsi_password: "{{ vault_influxdb_jitsi_password }}"
rsnapshot_user_public_key:  "{{ vault_rsnapshot_user_public_key }}"